<?php

/**
 * @file
 * Primary module hooks for Agenda Regulatoria module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

/**
 * Implements hook_form_alter().
 * @author 3desarrollo <3desarrollo@3dstudio.com>
 */
function webcrc_schedule_form_node_form_alter(&$form, $form_state, $form_id) {

  $node = $form_state->getFormObject()->getEntity();  

  if($node->getType() == 'agency_regulatory'){
    /* ===== ===== Campo fecha Inicial ===== ===== */
    $form['field_agency_date_initial']['widget'][0]['value']['#type'] = 'datelist';
    $form['field_agency_date_initial']['widget'][0]['value']['#date_part_order'] = ['year'];
    $form['field_agency_date_initial']['widget'][0]['value']['#date_year_range'] = '2015:+0';

    $form['field_agency_date_finished']['widget'][0]['value']['#type'] = 'datelist';
    $form['field_agency_date_finished']['widget'][0]['value']['#date_part_order'] = ['year'];
    $form['field_agency_date_finished']['widget'][0]['value']['#date_year_range'] = '2015:+1';
    //dpm($form['field_agency_two_trimester_ini']);

    $form['actions']['submit']['#submit'][] = 'webcrc_schedule_colors_submit';

    $form_state->getValue('title');
  }
}

/**
 * Funcion para agregar las fecha de agenda regultoria colors
 */
function webcrc_schedule_colors_submit(array &$form, \Drupal\Core\Form\FormStateInterface $form_state){
  $tri_initial = [];
  $tri_finished = [];
  
}
