<?php

/**
 * @file
 * Primary module hooks for Biblioteca Virtual module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Datetime\DrupalDateTime;
/**
 * Implements hook_form_alter().
 */
function webcrc_library_form_alter(&$form, $form_state, $form_id) {
  
}

 /**
 * Implements hook_form_views_exposed_form_alter()
 *
 */
function webcrc_library_form_views_exposed_form_alter(&$form, FormStateInterface $form_state) {
    //dpm($form);
    $date = new DrupalDateTime('now');
    if($form['#id'] == 'views-exposed-form-library-virtual-page-library-virtual'){

        /* ===== ===== TITULO ===== ===== */
        if (isset($form['palabras'])) $form['palabras']['#prefix'] = '<p class="h4 text-center text-white mb-3">'.t('Find the publication you have always been looking for').'</p>';

        /* ===== ===== PLACEHOLDER ===== ===== */
        $form['palabras-claves']['#attributes']['placeholder'] = t('Keywords: Colombia, Communication...');
        $form['autor']['#attributes']['placeholder'] = t('Author');

        /* ===== ===== LINEA ===== ===== */
        if (isset($form['tipo-documento']))$form['tipo-documento']['#prefix'] = '<hr class="bg-white"><div class="input__group d-flex">';

        /* ===== ===== END INPUT__GROUP ===== ===== */
        if(isset($form['created_wrapper'])){
            $form['created_wrapper']['#suffix'] = '</div>';
            $form['created_wrapper']['#attributes'] = [
                'class' => ['d-flex flex-column flex-md-row', 'justify-content-between'],
            ];

            $m = date('m', $date->getTimestamp());
            $y = date('Y', $date->getTimestamp());

            $form['created_wrapper']['created']['min']['#attributes']['placeholder'] = "01-01-$y";
            $form['created_wrapper']['created']['max']['#attributes']['placeholder'] = "30-".$m."-$y";
        }

        $form['actions']['#attributes'] = [
        'class' => ['text--md-center mt-3'],
        ];
        $form['actions']['submit']['#attributes'] = [
        'class' => ['btn-outline-light'],
        ];
        $form['actions']['reset']['#attributes'] = [
        'class' => ['btn-outline-light mt-3 mt-md-0'],
        ];
    }
}
  
/**
 * Implements hook_preprocess_form_element()
 */
function webcrc_library_preprocess_form_element(&$variables) {

    /* ===== ===== Nombre de proyecto ===== ===== */
    if(isset($variables['name'])){         
        /* ===== ===== SELECTOR ===== ===== */
        switch ($variables['name']) {

            case 'palabras':

                $variables['attributes'] = [
                    'class' => [
                        'input__primary d-flex flex-row',
                    ]
                ];
            
                $variables['label']['#attributes'] = [
                    'class' => [
                        'd-none',
                    ]
                ];
            
                $variables['label']['#prefix'] = '<img src="/themes/custom/webcrc/src/images/icono-lupa.svg" onerror="this.remove();" class="mx-3 my-2">';

            break;

            case 'tipo-documento': case 'formatos': case 'created[min]':  case 'created[max]':

                $variables['attributes'] = [
                    'class' => [
                    'my-3 input__group-item',
                    ]
                ];

                $variables['label']['#prefix'] = '<small>';
                $variables['label']['#suffix'] = '</small>';
                $variables['label']['#attributes'] = [
                    'class' => [
                    'm-0 px-3',
                    ]
                ];
                
            break;

            case 'palabras-claves': case 'autor':

                $variables['attributes'] = [
                    'class' => [
                    'my-3 input__group-item',
                    ]
                ];

                $variables['label']['#attributes'] = [
                    'class' => [
                    'd-none',
                    ]
                ];

            break;
        }
    }

    /* ===== ===== LABEL CREATED ===== ===== */
    if(isset($variables['name'])){
        //dpm($variables);
        if($variables['name'] == 'created[min]') $variables['label']['#title'] = t('Date I.');
        if($variables['name'] == 'created[max]') $variables['label']['#title'] = t('Date F.');
    }
}