<?php
/**
* @file
* Primary module hooks for webcrc_projects_regulatory module.
*
* @DCG
* This file is no longer required in Drupal 8.
* @see https://www.drupal.org/node/2217931
*/
use Drupal\Core\Form\FormStateInterface;
use Drupal\paragraphs\Entity\Paragraph;
use Drupal\Core\Render\Markup;
/**
* Implements hook_form_alter().
*/
function webcrc_projects_regulatory_form_alter (&$form, FormStateInterface $form_state, $form_id) {
  //Ocultar el campo de encuesta en los nodos del formulario
  $form['field_poll_content_useful']['widget'][0]['target_id']['#disabled'] = TRUE;
  $form['field_poll_content_useful']['widget'][0]['settings']['#open'] = FALSE;
  //dpm($form_state);  
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function webcrc_projects_regulatory_form_node_form_alter(&$form, $form_state, $form_id) {

  $node = $form_state->getFormObject()->getEntity();
  
  if($node->getType() == 'proyectos_regulatorios'){   
    
    $form['#attached']['library'][] = 'webcrc_projects_regulatory/webcrc_projects_regulatory';
    $form['field_resumen_proyecto']['widget'][0]['value']['#rows'] = 15;
    
  }
}

/**
 * Implements hook_preprocess_field().
 */
function webcrc_projects_regulatory_preprocess_field(&$variables, $hook){  
  $element = $variables['element'];
  if($element['#bundle'] == 'proyectos_regulatorios'){
    //Definir si existe algun documento final para ocultar o
    //mostrar las interacciones    
    $nid = \Drupal::routeMatch()->getParameter('node')->id();
    $field = \Drupal::entityTypeManager()->getStorage('node')->load($nid);
    $variables['document_defined'] = $field->get('field_projects_documents_endings')->getValue();
  }  
  
}

/**
 * Implements hook_preprocess_views_view_table()
 */
/*function webcrc_projects_regulatory_preprocess_views_view_table(&$variables){

  if($variables['theme_hook_original'] === 'views_view_table__projects_comments__page_projects_comments'){

   
    $tax_services = \Drupal::entityTypeManager()->getStorage('taxonomy_term')->loadTree('projects_services');
    $services = [];
    for($i=0; $i<count($tax_services); $i++){
      array_push($services, $tax_services[$i]->name);
    }   
    $variables['type_services'] = $services;

    
    $variables['type_typeprojects'] = $variables['view']->filter['field_tipo_proyecto_value']->getValueOptions();

    
    $variables['state'] = $variables['view']->filter['field_estado_proyectos_value']->getValueOptions();

  }
  
}*/

/**
 * Implements hook_preprocess_views_view_field()
 */
function webcrc_projects_regulatory_preprocess_views_view_field(&$variables) {
  $view = $variables['view'];
  $field = $variables['field'];
  $row = $variables['row'];
  
  if($view->storage->id() == 'projects_comments'){

    if($view->current_display == 'page_projects_comments'){      
        
      if($field->field == 'field_interacciones_proyectos'){

        $field = end($row->_entity->get('field_interacciones_proyectos')->getValue());
        $paragraph = Paragraph::load($field['target_id']);
        $definition_interactions = $paragraph->get('field_interactions_comments')[0]->getValue()['value'];

        if($definition_interactions == 0){
          $variables['output'] = ['#markup' => '<img src="/themes/custom/webcrc/src/images/aceptan-comentarios.svg" class="mr-3" alt="See interaction" onerror="this.remove();">'];          
        }else{
          $variables['output'] =['#markup' => '<img src="/themes/custom/webcrc/src/images/no-aceptan-comentarios.svg" class="mr-3" alt="See interaction" onerror="this.remove();">'];
        }
      }
      
      if($field->field == 'nothing'){

        $field = end($row->_entity->get('field_interacciones_proyectos')->getValue());
        $paragraph = Paragraph::load($field['target_id']);
        $dateTime = strtotime($paragraph->get('field_fecha_cierre_iteracciones')[0]->getValue()['value']);
        $variables['output'] = \Drupal::service('date.formatter')->format($dateTime, 'fecha_corta_webcrc');

      }
        
    }
  }

  //$variables['info'] = dump($field);
    
}

/**
 * Implements hook_form_views_exposed_form_alter()
 *
 */
function webcrc_projects_regulatory_form_views_exposed_form_alter(&$form, FormStateInterface $form_state) {
  //dpm($form);
  if($form['#id'] == 'views-exposed-form-projects-comments-page-projects-comments'){

    /* ===== ===== TITULO ===== ===== */
    if (isset($form['nombre_proyecto'])) $form['nombre_proyecto']['#prefix'] = '<p class="h4 text-center text-white mb-3">'.t('Find the project of your interest.').'</p>';

    /* ===== ===== LINEA ===== ===== */
    if (isset($form['estado_proyecto']))$form['estado_proyecto']['#prefix'] = '<hr class="bg-white"><div class="input__group d-flex">';

    /* ===== ===== END INPUT__GROUP ===== ===== */
    if(isset($form['servicio_proyecto'])) $form['servicio_proyecto']['#suffix'] = '</div>';

    $form['actions']['#attributes'] = [
      'class' => ['mt-3'],
    ];
    $form['actions']['submit']['#attributes'] = [
      'class' => ['btn-outline-light'],
    ];
    $form['actions']['reset']['#attributes'] = [
      'class' => ['btn-outline-light mt-3 mt-sm-0'],
    ];
  }
}

/**
 * Implements hook_preprocess_form_element()
 */
function webcrc_projects_regulatory_preprocess_form_element(&$variables) {
  /* ===== ===== Nombre de proyecto ===== ===== */
  if(isset($variables['name'])){

    /* ===== ===== SELECTOR ===== ===== */
    switch ($variables['name']) {

      case 'nombre_proyecto':

        $variables['attributes'] = [
          'class' => [
            'input__primary d-flex flex-row',
          ]
        ];
    
        $variables['label']['#attributes'] = [
          'class' => [
            'd-none',
          ]
        ];
    
        $variables['label']['#prefix'] = '<img src="/themes/custom/webcrc/src/images/icono-lupa.svg" onerror="this.remove();" class="mx-3 my-2">';
        
      break;

      case 'estado_proyecto': case 'tipo_proyecto': case 'servicio_proyecto':

        $variables['attributes'] = [
          'class' => [
            'my-3 input__group-item',
          ]
        ];

        $variables['label']['#prefix'] = '<small>';
        $variables['label']['#suffix'] = '</small>';
        $variables['label']['#attributes'] = [
          'class' => [
            'm-0 px-3',
          ]
        ];
          
      break;
    }       
  }
}

  
  
  