<?php
/**
* @file
* Primary module hooks for webcrc_projects_regulatory module.
*
* @DCG
* This file is no longer required in Drupal 8.
* @see https://www.drupal.org/node/2217931
*/
use Drupal\Core\Form\FormStateInterface;
/**
* Implements hook_form_alter().
*/
function webcrc_projects_regulatory_form_alter (&$form, FormStateInterface $form_state, $form_id) {
  if ($form['#id'] == "node-proyectos-regulatorios-edit-form" || $form['#id'] == "node-proyectos-regulatorios-form") {
    $form['#attached']['library'][] = 'webcrc_projects_regulatory/webcrc_projects_regulatory';
  }
}

/**
 * Implements hook_preprocess_field().
 */
function webcrc_projects_regulatory_preprocess_field(&$variables, $hook){  
  $element = $variables['element'];
  if($element['#bundle'] == 'proyectos_regulatorios'){
    //Definir si existe algun documento final para ocultar o
    //mostrar las interacciones    
    $nid = \Drupal::routeMatch()->getParameter('node')->id();
    $field = \Drupal::entityTypeManager()->getStorage('node')->load($nid);
    $variables['document_defined'] = $field->get('field_projects_documents_endings')->getValue();
  }  
  
}